spring:
  application:
    name: sun_service

  jpa:
    hibernate:
      ddl-auto: update

    database: mysql
#    使用InnoDB
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://49.234.22.26:3306/sjx?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: sjx123

#  cloud:
#    consul:
#      host: localhost
#      port: 8500




